---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # This older tag removes the Zsh exclusion in v0.11.0.1-1.
      - dependency-name: "https://github.com/shellcheck-py/shellcheck-py"
        versions: ["0.11.0.1"]
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
